In [1]:
#import pandas as pd
import numpy as np
import modin.pandas as pd
from zipfile import ZipFile

In [2]:
#inputs = pd.read_csv('Dataton_train.csv', sep =',',header = None,error_bad_lines= False)
#zip_file = ZipFile('/mnt/workstation/data/dt2020_base_evaluar.zip')
#inputs = pd.read_csv(zip_file.open("dt2020_base_evaluar.csv"), sep= ",")
#headers.columns

In [3]:
inputs = pd.read_csv("/mnt/workstation/data/Alomarrano/ToComplete_littlePig.csv")#, sep= ",", names =header)
#inputs = Totrain.iloc[:,1:]
inputs

id_registro  periodo   id_cli  fecha_nacimiento       edad genero  \
0        2089776#201908   201908  2089776        19840630.0  35.000000      M   
1        2089776#201909   201909  2089776        19840630.0  35.000000      M   
2        2089776#201907   201907  2089776        19840630.0  35.000000      M   
3        2089776#201903   201903  2089776        19840630.0  35.000000      M   
4        2089776#201911   201911  2089776        19840630.0  35.000000      M   
...                 ...      ...      ...               ...        ...    ...   
9527188  8596193#202011   202011  8596193        19740415.0  46.516085      F   
9527189  8616083#202011   202011  8616083        19850620.0  35.334702      M   
9527190  8670207#202011   202011  8670207        19740316.0  46.598220      M   
9527191  8677655#202011   202011  8677655        19780722.0  42.247775      F   
9527192  8692808#202011   202011  8692808        19801025.0  39.986311      F   

        estado_civil  nivel_academico            profesion  \
0         DIVORCIADO        TECNOLOGO  TECNOLOGIA SISTEMAS   
1         DIVORCIADO        TECNOLOGO  TECNOLOGIA SISTEMAS   
2         DIVORCIADO        TECNOLOGO  TECNOLOGIA SISTEMAS   
3         DIVORCIADO        TECNOLOGO  TECNOLOGIA SISTEMAS   
4         DIVORCIADO        TECNOLOGO  TECNOLOGIA SISTEMAS   
...              ...              ...                  ...   
9527188      SOLTERO    UNIVERSITARIO                OTROS   
9527189   NO INFORMA       NO INFORMA                  NaN   
9527190   DIVORCIADO       NO INFORMA                  NaN   
9527191       CASADO  ESPECIALIZACION             ECONOMIA   
9527192   NO INFORMA    UNIVERSITARIO                OTROS   

                         ocupacion  ...  saldo_prom3_tdc_mdo  cuota_tc_mdo  \
0                         Empleado  ...         0.000000e+00           0.0   
1                         Empleado  ...         0.000000e+00           0.0   
2                         Empleado  ...         0.000000e+00           0.0   
3                         Empleado  ...         0.000000e+00           0.0   
4                         Empleado  ...         0.000000e+00           0.0   
...                            ...  ...                  ...           ...   
9527188                   Empleado  ...         0.000000e+00           0.0   
9527189     Socio Empleado - Socio  ...         8.286667e+06      237000.0   
9527190  Profesional Independiente  ...         3.091700e+07    10350000.0   
9527191                   Empleado  ...         3.760867e+07     1953000.0   
9527192                   Empleado  ...         6.008000e+07     1141000.0   

         saldo_no_rot_mdo  cuota_libranza_sf  cant_oblig_tot_sf  \
0                903000.0                0.0                1.0   
1                903000.0                0.0                1.0   
2                903000.0                0.0                1.0   
3               2433000.0                0.0                1.0   
4                     0.0                0.0                0.0   
...                   ...                ...                ...   
9527188               0.0                0.0                2.0   
9527189           99000.0                0.0               12.0   
9527190          300000.0                0.0               17.0   
9527191       184811000.0                0.0               18.0   
9527192        25769000.0                0.0               14.0   

         cant_cast_ult_12m_sr           ind  rep_calif_cred  pol_centr_ext  \
0                         0.0  3.117155e+05               C            0.0   
1                         0.0  3.117155e+05               C            0.0   
2                         0.0  3.113060e+05               C            0.0   
3                         0.0  3.113060e+05               C            0.0   
4                         0.0  6.775160e+05               C            0.0   
...                       ...           ...             ...            ...   
952718

In [4]:
len(inputs['id_cli'].unique())

819841

inputs.columns =  ['periodo','id_cli','fecha_nacimiento','edad','genero','estado_civil',
    'nivel_academico','profesion','ocupacion','tipo_vivienda','ult_actual','categoria','codigo_ciiu',
    'ind_mora_vigente','cartera_castigada','ciudad_residencia','departamento_residencia','ciudad_laboral',
    'departamento_laboral','rechazo_credito','mora_max','cant_moras_30_ult_12_meses','cant_moras_60_ult_12_meses',
    'cant_moras_90_ult_12_meses','cupo_total_tc','tenencia_tc','cuota_tc_bancolombia','tiene_consumo','tiene_crediagil',
    'nro_tot_cuentas','ctas_activas','tiene_ctas_activas','ctas_embargadas','tiene_ctas_embargadas','pension_fopep',
    'cuota_cred_hipot','tiene_cred_hipo_1','tiene_cred_hipo_2','mediana_nom3','mediana_pen3','ingreso_nompen','cat_ingreso',
    'ingreso_final','cant_mora_30_tdc_ult_3m_sf','cant_mora_30_consum_ult_3m_sf','cuota_de_vivienda','cuota_de_consumo',
    'cuota_rotativos','cuota_tarjeta_de_credito','cuota_de_sector_solidario','cuota_sector_real_comercio','cupo_tc_mdo',
    'saldo_prom3_tdc_mdo','cuota_tc_mdo','saldo_no_rot_mdo','cuota_libranza_sf','cant_oblig_tot_sf','cant_cast_ult_12m_sr',
    'ind','rep_calif_cred','pol_centr_ext','convenio_lib','ingreso_nomina','ingreso_segurida_social','gasto_familiar']

In [5]:
inputs.loc[inputs['ind_mora_vigente']== '10']

To request implementation, send an email to feature_requests@modin.org.


Empty DataFrame
Columns: [id_registro, periodo, id_cli, fecha_nacimiento, edad, genero, estado_civil, nivel_academico, profesion, ocupacion, ult_actual, categoria, codigo_ciiu, ind_mora_vigente, cartera_castigada, ciudad_residencia, mora_max, cant_moras_30_ult_12_meses, cant_moras_60_ult_12_meses, cant_moras_90_ult_12_meses, cupo_total_tc, tenencia_tc, cuota_tc_bancolombia, tiene_consumo, tiene_crediagil, nro_tot_cuentas, ctas_activas, tiene_ctas_activas, ctas_embargadas, tiene_ctas_embargadas, pension_fopep, tiene_cred_hipo_1, tiene_cred_hipo_2, mediana_nom3, mediana_pen3, ingreso_nompen, ingreso_final, cant_mora_30_tdc_ult_3m_sf, cant_mora_30_consum_ult_3m_sf, cuota_de_vivienda, cuota_de_consumo, cuota_rotativos, cuota_tarjeta_de_credito, cuota_de_sector_solidario, cuota_sector_real_comercio, cupo_tc_mdo, saldo_prom3_tdc_mdo, cuota_tc_mdo, saldo_no_rot_mdo, cuota_libranza_sf, cant_oblig_tot_sf, cant_cast_ult_12m_sr, ind, rep_calif_cred, pol_centr_ext, gasto_familiar]
Index: []

[0 rows x 56 columns]

#elimina los archivos corruptos
borrar = inputs.loc[inputs['rechazo_credito'] == 'ANTIOQUIA                                         ','periodo'].index.tolist()
inputs.drop([6709248,6715408, 6715409, 6715410, 6715411, 6715412, 6715413, 6715414, 6715415, 6715416, 6715417, 6715418,
            6715419, 6715420, 6715421, 6715422, 6715423, 6715424, 6715425, 6715426], inplace = True)

In [6]:
inputs.drop_duplicates(inplace = True)

In [7]:
#backup
#inputs.to_csv('inputs.csv')

In [8]:
pd.set_option('display.max_columns', None)
inputs.head()

id_registro  periodo   id_cli  fecha_nacimiento  edad genero  \
0  2089776#201908   201908  2089776        19840630.0  35.0      M   
1  2089776#201909   201909  2089776        19840630.0  35.0      M   
2  2089776#201907   201907  2089776        19840630.0  35.0      M   
3  2089776#201903   201903  2089776        19840630.0  35.0      M   
4  2089776#201911   201911  2089776        19840630.0  35.0      M   

  estado_civil  cuota_libranza_sf  cant_oblig_tot_sf  cant_cast_ult_12m_sr  \
0   DIVORCIADO                0.0                1.0                   0.0   
1   DIVORCIADO                0.0                1.0                   0.0   
2   DIVORCIADO                0.0                1.0                   0.0   
3   DIVORCIADO                0.0                1.0                   0.0   
4   DIVORCIADO                0.0                0.0                   0.0   

[5 rows x 56 columns]

## Mirar los Null

In [9]:
sum(inputs['periodo'].isnull())

0

In [10]:
print(sum(inputs['id_cli'].isnull()))
print(len(inputs['id_cli'].unique()))

0
819841


In [11]:
sum(inputs['fecha_nacimiento'].isnull())

0

In [12]:
inputs.loc[inputs['edad'] == '\\N','edad'] = np.nan
inputs['edad'] = inputs['edad'].astype(float)
inputs['edad']= inputs['edad'].round()
inputs
sum(inputs['edad'].isnull())

0

In [13]:
print(inputs['genero'].unique())
print(sum(inputs['genero'] == ' '))
inputs.loc[inputs['genero'] == ' ', 'genero'] = np.nan

['M' 'F']
0


In [14]:
print(inputs['estado_civil'].unique())
inputs.loc[inputs['estado_civil'].isin(['NO INFORMA','\\N']),'estado_civil'] = 'NO INFORMA'
sum(inputs['estado_civil'] == 'NO INFORMA')

['DIVORCIADO' 'UNION LIBRE' 'SOLTERO' 'CASADO' 'VIUDO' 'NO INFORMA' 'OTRO'
 nan]


18552

In [15]:
inputs.loc[inputs['nivel_academico'].isin(['NO INFORMA','SIN INFORMACION']),'nivel_academico'] = 'NO INFORMA'
print(inputs['nivel_academico'].unique())

['TECNOLOGO' 'UNIVERSITARIO' 'ESPECIALIZACION' 'BACHILLER' 'PRIMARIO'
 'NINGUNO' 'NO INFORMA']


In [16]:
inputs['profesion'].unique()

array(['TECNOLOGIA SISTEMAS', 'VETERINARIA', 'OTROS',
       'COMUNICACION SOCIAL', 'INGENIERIA DE PETROLEOS', 'ADMINISTRACION',
       'DERECHO', 'BACTERIOLOGIA', 'INGENIERO METALURGICO', 'INGENIERO',
       'INGENIERIA DE SISTEMAS', 'ODONTOLOGIA', 'TECNOLOGIA ELECTRICIDAD',
       'CONTADURIA', 'NINGUNA', 'EDUCACION', 'QUIMICA FARMACEUTICA',
       'COMERCIO INTERNACIONAL', 'CONSTRUCCION CIVIL',
       'INGENIERIA ADMINISTRATIVA', 'INGENIERIA CIVIL',
       'INGENIERO ELECTRONICO', 'INGENIERIA AMBIENTAL', 'TRABAJO SOCIAL',
       'TECNOLOGIA EN ADMINISTRACION', 'ECONOMIA', 'INGENIERIA AGRICOLA',
       'AGRONOMIA', 'MERCADOTECNIA', 'ARQUITECTURA', 'AUXILIAR CONTABLE',
       'ENFERMERIA', 'DECORADORES Y DISEÑADORES COMERCIALES',
       'INGENIERIA ELECTRICA', 'DISEÑO Y PUBLICIDAD',
       'TECNOLOGIA EN CIENCIAS DE LA SALUD', 'PSICOLOGIA', 'MEDICINA',
       'INGENIERIA FINANCIERA', 'INGENIERIA MECANICA',
       'INGENIERIA SANITARIA', 'AUXILIAR DE ENFERMERIA',
       'INGENIERIA IND

In [17]:
inputs['ocupacion'].unique()
inputs.loc[inputs['ocupacion'] == '\\N', 'ocupacion'] = 'vacio'
# sumar  ANTROPOLOGOS Y ESPECIALISTA SIMIL, ARCHIVEROS Y ENCARGA DE MUSEO 
# sumar '\\N' y 'Otro'

inputs.loc[inputs['tipo_vivienda'] == '\\N','tipo_vivienda'] = 'NO INFORMA'
inputs['tipo_vivienda'].unique()

In [18]:
inputs.loc[inputs['ult_actual'] == '\\N'] = np.NaN
inputs['ult_actual'] = inputs['ult_actual'].astype('float')
print(sum(inputs['ult_actual'].isnull()))
print(inputs['ult_actual'].unique())

0
[20180526. 20200902. 20200131. ... 20170130. 20170206. 20170312.]


In [19]:
inputs['categoria'].unique()
inputs.loc[inputs['categoria'] == '\\N','categoria'] = '0'
#inputs['categoria'] = inputs['categoria'].astype('int')
print(sum(inputs['categoria'] == 0))

637


In [20]:
inputs['codigo_ciiu'].unique()

array([1.000e+01, 9.609e+03, 8.691e+03, 1.410e+02, 8.692e+03, 8.622e+03,
       0.000e+00, 5.223e+03, 4.799e+03, 9.000e+01, 7.110e+03, 1.690e+03,
       8.211e+03, 8.299e+03, 4.665e+03, 8.621e+03, 6.621e+03, 7.490e+03,
       5.920e+03, 7.020e+03, 4.645e+03, 7.120e+03, 6.920e+03, 6.910e+03,
       7.730e+03, 4.330e+03, 9.329e+03, 4.321e+03, 1.051e+03, 6.202e+03,
       6.810e+03, 6.209e+03, 4.652e+03, 4.774e+03, 4.759e+03, 4.761e+03,
       4.741e+03, 9.512e+03, 8.610e+03, 8.541e+03, 2.825e+03, 7.310e+03,
       8.512e+03, 7.010e+03, 7.500e+03, 3.312e+03, 4.719e+03, 4.923e+03,
       4.620e+03, 6.820e+03, 4.659e+03, 1.210e+02, 4.290e+03, 5.619e+03,
       4.669e+03, 5.511e+03, 8.551e+03, 1.811e+03, 4.729e+03, 4.723e+03,
       5.630e+03, 4.752e+03, 3.811e+03, 1.220e+02, 6.201e+03, 4.921e+03,
       4.711e+03, 8.430e+03, 5.911e+03, 4.329e+03, 6.619e+03, 4.724e+03,
       8.553e+03, 3.210e+03, 1.812e+03, 9.602e+03, 6.120e+03, 9.003e+03,
       1.709e+03, 1.410e+03, 3.315e+03, 4.754e+03, 

In [21]:
inputs

id_registro  periodo   id_cli  fecha_nacimiento  edad genero  \
0        2089776#201908   201908  2089776        19840630.0  35.0      M   
1        2089776#201909   201909  2089776        19840630.0  35.0      M   
2        2089776#201907   201907  2089776        19840630.0  35.0      M   
3        2089776#201903   201903  2089776        19840630.0  35.0      M   
4        2089776#201911   201911  2089776        19840630.0  35.0      M   
...                 ...      ...      ...               ...   ...    ...   
9527188  8596193#202011   202011  8596193        19740415.0  47.0      F   
9527189  8616083#202011   202011  8616083        19850620.0  35.0      M   
9527190  8670207#202011   202011  8670207        19740316.0  47.0      M   
9527191  8677655#202011   202011  8677655        19780722.0  42.0      F   
9527192  8692808#202011   202011  8692808        19801025.0  40.0      F   

        estado_civil  cuota_libranza_sf  cant_oblig_tot_sf  \
0         DIVORCIADO                0.0                1.0   
1         DIVORCIADO                0.0                1.0   
2         DIVORCIADO                0.0                1.0   
3         DIVORCIADO                0.0                1.0   
4         DIVORCIADO                0.0                0.0   
...              ...                ...                ...   
9527188      SOLTERO                0.0                2.0   
9527189   NO INFORMA                0.0               12.0   
9527190   DIVORCIADO                0.0               17.0   
9527191       CASADO                0.0               18.0   
9527192   NO INFORMA                0.0               14.0   

         cant_cast_ult_12m_sr           ind rep_calif_cred  pol_centr_ext  \
0                         0.0  3.117155e+05              C            0.0   
1                         0.0  3.117155e+05              C            0.0   
2                         0.0  3.113060e+05              C            0.0   
3                         0.0  3.113060e+05              C            0.0   
4                         0.0  6.775160e+05              C            0.0   
...                       ...           ...            ...            ...   
9527188                   0.0  2.101424e+06              A            0.0   
9527189                   0.0  1.170550e+07              C            0.0   
9527190                   0.0 -4.154790e+07              D            0.0   
9527191                   0.0  5.313457e+06              B            0.0   
9527192                   0.0 -2.172737e+06              E            0.0   

         gasto_familiar  
0              232526.0  
1              265900.0  
2              243052.0  
3              276014.0  
4              418866.0  
...                 ...  
9527188             NaN  
9527189             NaN  
9527190             NaN  
9527191             NaN  
9527192             NaN  

[9527193 rows x 56 columns]

In [22]:
print(inputs['ind_mora_vigente'].unique())
print(sum(inputs['ind_mora_vigente'] == '\\N'))
inputs.loc[inputs['ind_mora_vigente'] == '\\N','ind_mora_vigente'] = np.nan
#inputs.dropna(inplace = True)
#inputs.loc[inputs['ind_mora_vigente'] == '\\N','ind_mora_vigente'] = 0
inputs.loc[inputs['ind_mora_vigente'] == 0,'ind_mora_vigente'] = False
inputs.loc[inputs['ind_mora_vigente'] == 1,'ind_mora_vigente'] = True
inputs['ind_mora_vigente'] = inputs['ind_mora_vigente'].astype(bool)

[True 'True' 'N' 'S' nan]
0


In [23]:
print(inputs['cartera_castigada'].unique())
print(sum(inputs['cartera_castigada'] == '\\N'))
inputs.loc[inputs['cartera_castigada'] == 0,'cartera_castigada'] = False
inputs.loc[inputs['cartera_castigada'] == 1,'cartera_castigada'] = True
inputs['cartera_castigada'] = inputs['cartera_castigada'].astype(bool)

[True 'True' 'N' 'S' nan]
0


In [24]:
#quita los espacios vacios
inputs['ciudad_residencia'] = inputs['ciudad_residencia'].str.strip()
inputs['ciudad_residencia'].unique()

array(['CALI', 'GARZON', 'MEDELLIN', ..., 'SANTA MARIA (BOYACA)',
       'AMBALEMA - URAMITA', 'SIBUNDOY - SIBUNDOY'], dtype=object)

inputs['departamento_residencia'] = inputs['departamento_residencia'].str.strip()
inputs['departamento_residencia'].unique()

inputs['ciudad_laboral'] = inputs['ciudad_laboral'].str.strip()
inputs['ciudad_laboral'].unique()

inputs['departamento_laboral'] = inputs['departamento_laboral'].str.strip()
inputs['departamento_laboral'].unique()

print(inputs['rechazo_credito'].unique())
sum(inputs['rechazo_credito'] == '\\N')

In [25]:
print(inputs['mora_max'].unique())
print(sum(inputs['mora_max'] == '\\N'))
inputs.loc[inputs['mora_max'] == '\\N','mora_max'] = np.nan
inputs['mora_max'] = inputs['mora_max'].astype(float)

[0.000e+00 3.000e+00 2.800e+01 1.000e+00 1.600e+01 1.400e+01 1.300e+01
 1.200e+01 8.000e+00 2.000e+00 7.000e+00 3.700e+01 7.000e+01 4.000e+01
 2.000e+01 2.400e+01 1.500e+01 4.000e+00 5.000e+00 2.200e+01 2.270e+02
 2.120e+02 1.700e+01 1.900e+01 2.100e+01 2.700e+01 6.000e+01 2.900e+01
 3.900e+01 2.600e+01 1.800e+01 3.400e+01 5.900e+01 2.500e+01 1.050e+02
 7.500e+01 3.000e+01 6.000e+00 5.700e+01 1.170e+02 4.400e+01 3.200e+01
 6.100e+01 5.800e+01 1.000e+01 9.000e+00 4.500e+01 4.800e+01 8.000e+01
 8.500e+01 5.500e+01 3.300e+01 3.100e+01 4.600e+01 4.300e+01 3.800e+01
 1.800e+02 2.100e+02 2.300e+01 1.100e+01 8.900e+01 3.500e+01 2.140e+02
 6.500e+01 1.270e+02 1.580e+02 9.700e+01 7.600e+01 1.040e+02 1.220e+02
 1.530e+02 9.500e+01 9.600e+01 4.900e+01 8.800e+01 2.530e+02 1.330e+02
 7.300e+01 1.630e+02 2.230e+02 1.930e+02 4.200e+01 1.000e+02 1.320e+02
 5.000e+01 1.650e+02 4.700e+01 1.350e+02 2.450e+02 6.800e+01 4.100e+01
 9.100e+01 1.030e+02 5.400e+01 1.480e+02 1.190e+02 1.780e+02 7.900e+01
 3.600

0


inputs.to_csv('test_inputs2.csv')

In [26]:
inputs.head()

id_registro  periodo   id_cli  fecha_nacimiento  edad genero  \
0  2089776#201908   201908  2089776        19840630.0  35.0      M   
1  2089776#201909   201909  2089776        19840630.0  35.0      M   
2  2089776#201907   201907  2089776        19840630.0  35.0      M   
3  2089776#201903   201903  2089776        19840630.0  35.0      M   
4  2089776#201911   201911  2089776        19840630.0  35.0      M   

  estado_civil  cuota_libranza_sf  cant_oblig_tot_sf  cant_cast_ult_12m_sr  \
0   DIVORCIADO                0.0                1.0                   0.0   
1   DIVORCIADO                0.0                1.0                   0.0   
2   DIVORCIADO                0.0                1.0                   0.0   
3   DIVORCIADO                0.0                1.0                   0.0   
4   DIVORCIADO                0.0                0.0                   0.0   

[5 rows x 56 columns]

## Parte 2

import pandas as pd
import numpy as np

inputs = pd.read_csv('test_inputs2.csv', sep =',')

In [27]:
pd.set_option('display.max_columns', None)
inputs.head()

id_registro  periodo   id_cli  fecha_nacimiento  edad genero  \
0  2089776#201908   201908  2089776        19840630.0  35.0      M   
1  2089776#201909   201909  2089776        19840630.0  35.0      M   
2  2089776#201907   201907  2089776        19840630.0  35.0      M   
3  2089776#201903   201903  2089776        19840630.0  35.0      M   
4  2089776#201911   201911  2089776        19840630.0  35.0      M   

  estado_civil  cuota_libranza_sf  cant_oblig_tot_sf  cant_cast_ult_12m_sr  \
0   DIVORCIADO                0.0                1.0                   0.0   
1   DIVORCIADO                0.0                1.0                   0.0   
2   DIVORCIADO                0.0                1.0                   0.0   
3   DIVORCIADO                0.0                1.0                   0.0   
4   DIVORCIADO                0.0                0.0                   0.0   

[5 rows x 56 columns]

In [28]:
print(inputs['cant_moras_30_ult_12_meses'].unique())
inputs.loc[inputs['cant_moras_30_ult_12_meses'] == '\\N','cant_moras_30_ult_12_meses'] = np.nan
inputs['cant_moras_30_ult_12_meses'] = inputs['cant_moras_30_ult_12_meses'].astype(float)

[ 0.  1.  3.  2. 12. 11.  7.  8.  6.  4.  5. 10.  9.]


In [29]:
print(inputs['cant_moras_60_ult_12_meses'].unique())
inputs.loc[inputs['cant_moras_60_ult_12_meses'] == '\\N','cant_moras_60_ult_12_meses'] = np.nan
inputs['cant_moras_60_ult_12_meses'] = inputs['cant_moras_60_ult_12_meses'].astype(float)

[ 0.  1. 11.  2. 10.  3.  4.  5.  8.  7. 12.  6.  9.]


In [30]:
print(inputs['cant_moras_90_ult_12_meses'].unique())
inputs.loc[inputs['cant_moras_90_ult_12_meses'] == '\\N','cant_moras_90_ult_12_meses'] = np.nan
inputs['cant_moras_90_ult_12_meses'] = inputs['cant_moras_90_ult_12_meses'].astype(float)

[ 0.  8.  2.  9.  1.  3.  7. 12.  6. 10.  4. 11.  5.]


In [31]:
print(inputs['cupo_total_tc'].unique())
print(sum(inputs['cupo_total_tc'].isnull()))

[       0.  6000000.  3000000. ... 70082000. 30070000.  5817000.]
0


In [32]:
print(inputs['tenencia_tc'].unique())
inputs.loc[inputs['tenencia_tc']=='NO','tenencia_tc'] = False
inputs.loc[inputs['tenencia_tc']=='SI','tenencia_tc'] = True
inputs['tenencia_tc']=inputs['tenencia_tc'].astype(bool)

[False True 'True' 'False' 'NO' 'SI']


In [33]:
print(inputs['cuota_tc_bancolombia'].unique())
print(sum(inputs['cuota_tc_bancolombia'].isnull()))

[      0.      413837.5005  126000.     ...  387082.575   508134.276
 7620965.514 ]
0


In [34]:
print(inputs['tiene_consumo'].unique())
inputs.loc[inputs['tiene_consumo']=='\\N','tiene_consumo'] = False
inputs.loc[inputs['tiene_consumo']=='X','tiene_consumo'] = True
inputs['tiene_consumo']=inputs['tiene_consumo'].astype(bool)
print(sum(inputs['tiene_consumo'].isnull()))

[False True 'True' 'False' nan 'X']
0


In [35]:
print(inputs['tiene_crediagil'].unique())
inputs.loc[inputs['tiene_crediagil']=='\\N','tiene_crediagil'] = False
inputs.loc[inputs['tiene_crediagil']=='X','tiene_crediagil'] = True
inputs['tiene_crediagil']=inputs['tiene_crediagil'].astype(bool)
print(sum(inputs['tiene_crediagil'].isnull()))

[False True 'False' 'True' nan 'X']
0


In [36]:
print(inputs['nro_tot_cuentas'].unique())
inputs.loc[inputs['nro_tot_cuentas']=='\\N','nro_tot_cuentas'] = np.nan
inputs['nro_tot_cuentas'] = inputs['nro_tot_cuentas'].astype(float)

[ 1.  2.  0.  3.  4.  5.  6.  9.  7.  8. 23. 11. 30. 36. 15. 35. 24. 14.]


In [37]:
print(inputs['ctas_activas'].unique())
inputs.loc[inputs['ctas_activas']=='\\N','ctas_activas'] = np.nan
inputs['ctas_activas'] = inputs['ctas_activas'].astype(float)

[ 1.  2.  0.  3.  4.  5.  6.  9.  7.  8. 23. 11. 30. 36. 15. 10. 35. 24.
 14.]


In [38]:
print(inputs['tiene_ctas_activas'].unique())
inputs.loc[inputs['tiene_ctas_activas']=='\\N','tiene_ctas_activas'] = False
inputs.loc[inputs['tiene_ctas_activas']=='X','tiene_ctas_activas'] = True
inputs['tiene_ctas_activas']=inputs['tiene_ctas_activas'].astype(bool)
print(sum(inputs['tiene_ctas_activas'].isnull()))


[True False 'True' 'False' 'X' nan]
0


In [39]:
print(inputs['ctas_embargadas'].unique())
inputs.loc[inputs['ctas_embargadas']=='\\N','ctas_embargadas'] = np.nan
inputs['ctas_embargadas'] = inputs['ctas_embargadas'].astype(float)

[0. 1. 2. 3. 4.]


In [40]:
print(inputs['tiene_ctas_embargadas'].unique())
inputs.loc[inputs['tiene_ctas_embargadas']=='\\N','tiene_ctas_embargadas'] = False
inputs.loc[inputs['tiene_ctas_embargadas']=='X','tiene_ctas_embargadas'] = True
inputs['tiene_ctas_embargadas']=inputs['tiene_ctas_embargadas'].astype(bool)
print(sum(inputs['tiene_ctas_embargadas'].isnull()))

[False True 'False' 'True' nan 'X']
0


In [41]:
print(inputs['pension_fopep'].unique())
inputs.loc[inputs['pension_fopep']=='\\N','pension_fopep'] = False
inputs.loc[inputs['pension_fopep']=='X','pension_fopep'] = True
inputs['pension_fopep']=inputs['pension_fopep'].astype(bool)
print(sum(inputs['pension_fopep'].isnull()))

[False True 'False' 'True' nan 'X']
0


print(inputs['cuota_cred_hipot'].unique())
inputs.loc[inputs['cuota_cred_hipot']=='\\N','cuota_cred_hipot'] = np.nan
inputs['cuota_cred_hipot'] = inputs['cuota_cred_hipot'].astype(float)

In [42]:
print(inputs['tiene_cred_hipo_1'].unique())
inputs.loc[inputs['tiene_cred_hipo_1']=='\\N','tiene_cred_hipo_1'] = False
inputs.loc[inputs['tiene_cred_hipo_1']=='X','tiene_cred_hipo_1'] = True
inputs['tiene_cred_hipo_1']=inputs['tiene_cred_hipo_1'].astype(bool)
print(sum(inputs['tiene_cred_hipo_1'].isnull()))

[False True 'False' 'True' nan 'X']
0


In [43]:
print(inputs['tiene_cred_hipo_2'].unique())
inputs.loc[inputs['tiene_cred_hipo_2']=='\\N','tiene_cred_hipo_2'] = False
inputs.loc[inputs['tiene_cred_hipo_2']=='X','tiene_cred_hipo_2'] = True
inputs['tiene_cred_hipo_2']=inputs['tiene_cred_hipo_2'].astype(bool)
print(sum(inputs['tiene_cred_hipo_2'].isnull()))

[False True 'False' 'True' nan 'X']
0


In [44]:
print(inputs['mediana_nom3'].unique())

[ 1255032.  1282673.        0. ...  1922668. 14956096. 11916465.]


In [45]:
print(inputs['mediana_pen3'].unique())

[      0. 1918483. 1429361. ... 1096732. 1469267. 2065445.]


In [46]:
print(inputs['ingreso_nompen'].unique())

[ 1255032.  1282673.        0. ...  1922668. 14956096. 11916465.]


print(inputs['cat_ingreso'].unique())
inputs.loc[inputs['cat_ingreso']=='\\N','cat_ingreso'] = np.nan

In [47]:
print(inputs['ingreso_final'].unique())
inputs.loc[inputs['ingreso_final']=='\\N','ingreso_final'] = np.nan
inputs['ingreso_final'] = inputs['ingreso_final'].astype(float)

[ 1173431.  1172612.  1355032. ... 26913722. 14481371.  8407800.]


In [48]:
print(inputs['cant_mora_30_tdc_ult_3m_sf'].unique())
inputs.loc[inputs['cant_mora_30_tdc_ult_3m_sf']=='\\N','cant_mora_30_tdc_ult_3m_sf'] = np.nan
inputs['cant_mora_30_tdc_ult_3m_sf'] = inputs['cant_mora_30_tdc_ult_3m_sf'].astype(float)

[ 0.  1.  2.  4.  3.  6.  8.  5.  7.  9. 11. 10.]


In [49]:
print(inputs['cant_mora_30_consum_ult_3m_sf'].unique())
inputs.loc[inputs['cant_mora_30_consum_ult_3m_sf']=='\\N','cant_mora_30_consum_ult_3m_sf'] = np.nan
inputs['cant_mora_30_consum_ult_3m_sf'] = inputs['cant_mora_30_consum_ult_3m_sf'].astype(float)

[  0.   1.   2.   6.   4.   3.   5.   9.  15.  10.   7.   8.  11.  12.
  13.  14.  60.  41.  20.  42.  18.  16.  24.  17.  23.  34.  30.  45.
  19.  32.  21.  58.  56.  22.  35.  48.  36.  46.  38.  63.  59.  28.
  29.  27.  25.  26.  40. 115.  39.  52.  33.  66.  67.  50.  70.  86.
  37.  51.  54.  31.  62.  44. 144.  98.  91. 101. 100.  96.  68.  55.
  57.  80. 120.  82.  53.  79.  47.  72.  73.  89. 150.]


In [50]:
print(inputs['cuota_de_vivienda'].unique())

[      0.   1317000.   1331000.   ... 1071414.15  317405.72 9794649.65]


In [51]:
print(inputs['cuota_de_consumo'].unique())

[  275000.          0.     164000.   ... 15648142.7   1380417.
  2232547.58]


In [52]:
print(inputs['cuota_rotativos'].unique())

[      0.   33000.   17000. ... 4485000. 3334000. 3469000.]


In [53]:
print(inputs['cuota_tarjeta_de_credito'].unique())

[       0.    87000.    49000. ... 13170000. 23911000. 26334000.]


In [54]:
print(inputs['cuota_de_sector_solidario'].unique())

[       0.    45000.   522000. ...  5136000. 18258000. 11200000.]


In [55]:
print(inputs['cuota_sector_real_comercio'].unique())

[0.000000e+00 1.250000e+05 2.230000e+05 ... 1.082166e+09 7.388000e+06
 7.801000e+06]


In [56]:
print(inputs['cupo_tc_mdo'].unique())

[0.00000e+00 4.27000e+05 5.80000e+05 ... 1.07305e+08 1.21890e+08
 1.02025e+08]


In [57]:
print(inputs['saldo_prom3_tdc_mdo'].unique())

[       0.      427000.      335000.    ... 21942666.667 37608666.667
 60080000.   ]


In [58]:
print(inputs['cuota_tc_mdo'].unique())

[0.0000e+00 1.9500e+05 5.2000e+04 ... 3.3673e+07 3.4848e+07 5.3136e+07]


In [59]:
print(inputs['saldo_no_rot_mdo'].unique())

[9.03000e+05 2.43300e+06 0.00000e+00 ... 3.55074e+08 1.95269e+08
 3.18689e+08]


In [60]:
print(inputs['cuota_libranza_sf'].unique())

[      0.  501000. 1054000. ... 4842000. 6854000. 6559000.]


In [61]:
print(inputs['cant_oblig_tot_sf'].unique())
inputs.loc[inputs['cant_oblig_tot_sf']=='\\N','cant_oblig_tot_sf'] = np.nan
inputs['cant_oblig_tot_sf'] = inputs['cant_oblig_tot_sf'].astype(float)

[  1.   0.   3.   2.  10.   6.   9.  12.   4.   5.   7.   8.  13.  11.
  15.  14.  20.  19.  23.  25.  22.  17.  21.  18.  16.  24.  26.  28.
  27.  29.  36.  39.  30.  31.  34.  32.  50.  48.  40.  33.  37.  55.
  61.  74.  69.  43.  38.  35.  45.  42.  41.  60.  44.  47.  49.  58.
  64.  59.  46.  52.  53.  51.  57.  54.  76.  65.  62.  75.  84.  77.
  72.  67.  81.  68.  66.  56.  93. 104.  80.  71. 102.  89.  63.  70.
  78.  94. 112. 113.  82. 139. 109. 103. 127.  85.  87.  73.  79.  92.
  91.  88. 105.  97.]


In [62]:
print(inputs['cant_cast_ult_12m_sr'].unique())
inputs.loc[inputs['cant_cast_ult_12m_sr']=='\\N','cant_cast_ult_12m_sr'] = np.nan
inputs['cant_cast_ult_12m_sr'] = inputs['cant_cast_ult_12m_sr'].astype(float)

[  0.   1.   5.  19.   3.   4.  10.  11.   2.  22.   6.  66.   8.  88.
  12.  18.   7.   9.  41.  21.  33.  17.  77.  48.  20.  44.  42.  29.
  55.  32.  16.  13.  14.  54.  64.  27.  31.  38.  35. 110.  63.  37.
  52.  99.  23.  87.  43.  85.  15.  45.  91.  40.  34.  26.  53.  49.
  93.  69.  28.  58.  24.  78.  51.  76. 121.  30.  62. 132.  75.  65.
  25.  47.  96.  36.  50.  57. 108.  73.  74.  46. 506.  68.  83. 176.
  94. 165.  90.  71.  56.  39. 118.  61. 120. 104.  60.  59.  95. 144.
  98.  97.  86.  67. 139. 153. 143. 206. 267. 113. 117. 197.  82. 112.
  80. 308. 154.  84. 198. 105. 134. 111.  72. 264. 102. 231. 175.  92.
 129. 209.  70. 187.  89. 160. 128. 528.]


In [63]:
print(inputs['ind'].unique())
inputs.loc[inputs['ind']=='\\N','ind'] = np.nan
inputs['ind'] = inputs['ind'].astype(float)

[   311715.5       311306.        677516.     ... -41547904.85
   5313457.0125  -2172736.58  ]


In [64]:
print(inputs['rep_calif_cred'].unique())

['C' 'B' 'D' 'G' 'F' 'A' 'H' 'E' 'SIN INFO']


In [65]:
print(inputs['pol_centr_ext'].unique())
inputs.loc[inputs['pol_centr_ext']=='\\N','pol_centr_ext'] = np.nan
inputs['pol_centr_ext'] = inputs['pol_centr_ext'].astype(float)

[ 0.  8. 11.  7.  4.  1. 12. 10. 14. 13.  5.  2.  3.  9.  6. 15. 16. 17.
 18. 19. 20. 21. 22. 24. nan]


print(inputs['convenio_lib'].unique())
inputs.loc[inputs['convenio_lib']=='\\N','convenio_lib'] = np.nan
inputs.loc[inputs['convenio_lib']=='REVISAR CONVENIOS','convenio_lib'] = np.nan
inputs['convenio_lib'] = inputs['convenio_lib'].astype(float)

print(inputs['ingreso_nomina'].unique())
inputs.loc[inputs['ingreso_nomina']=='\\N','ingreso_nomina'] = np.nan
inputs['ingreso_nomina'] = inputs['ingreso_nomina'].astype(float)

print(inputs['ingreso_segurida_social'].unique())
inputs.loc[inputs['ingreso_segurida_social']=='\\N','ingreso_segurida_social'] = np.nan
inputs['ingreso_segurida_social'] = inputs['ingreso_segurida_social'].astype(float)

print(inputs['gasto_familiar'].unique())

In [68]:
inputs.columns

Index(['id_registro', 'periodo', 'id_cli', 'fecha_nacimiento', 'edad',
       'genero', 'estado_civil', 'nivel_academico', 'profesion', 'ocupacion',
       'ult_actual', 'categoria', 'codigo_ciiu', 'ind_mora_vigente',
       'cartera_castigada', 'ciudad_residencia', 'mora_max',
       'cant_moras_30_ult_12_meses', 'cant_moras_60_ult_12_meses',
       'cant_moras_90_ult_12_meses', 'cupo_total_tc', 'tenencia_tc',
       'cuota_tc_bancolombia', 'tiene_consumo', 'tiene_crediagil',
       'nro_tot_cuentas', 'ctas_activas', 'tiene_ctas_activas',
       'ctas_embargadas', 'tiene_ctas_embargadas', 'pension_fopep',
       'tiene_cred_hipo_1', 'tiene_cred_hipo_2', 'mediana_nom3',
       'mediana_pen3', 'ingreso_nompen', 'ingreso_final',
       'cant_mora_30_tdc_ult_3m_sf', 'cant_mora_30_consum_ult_3m_sf',
       'cuota_de_vivienda', 'cuota_de_consumo', 'cuota_rotativos',
       'cuota_tarjeta_de_credito', 'cuota_de_sector_solidario',
       'cuota_sector_real_comercio', 'cupo_tc_mdo', 'saldo_pro

In [69]:
inputs.shape

(9527193, 56)

In [70]:
inputs.describe(include = 'all').T

IndexError:  positional indexers are out-of-bounds

count 
 unique 
 top 
 freq 
 mean 
 std 
 min 
 25% 
 50% 
 75% 
 max 
 
 
 
 
 id_registro 
 9527193 
 9527193 
 8440976#201910 
 1 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 periodo 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 201959 
 49.6603 
 201902 
 201907 
 202001 
 202007 
 202011 
 
 
 id_cli 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 2.9855e+06 
 2.53255e+06 
 3 
 1.0826e+06 
 2.25538e+06 
 3.94006e+06 
 8.7048e+06 
 
 
 fecha_nacimiento 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 1.97712e+07 
 129659 
 1.90006e+07 
 1.96908e+07 
 1.98009e+07 
 1.98707e+07 
 2.02009e+07 
 
 
 edad 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 42.3635 
 12.9779 
 0 
 32 
 39 
 50 
 119 
 
 
 genero 
 9527193 
 2 
 F 
 4941539 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 estado_civil 
 9526675 
 7 
 SOLTERO 
 4609348 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 nivel_academico 
 9527193 
 7 
 UNIVERSITARIO 
 5711314 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 profesion 
 9477607 
 87 
 OTROS 
 3561488 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 ocupacion 
 9527177 
 17 
 Empleado 
 7149136 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 ult_actual 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 2.01905e+07 
 11867.9 
 0 
 2.01901e+07 
 2.01907e+07 
 2.02001e+07 
 2.0201e+07 
 
 
 categoria 
 9.52387e+06 
 NaN 
 NaN 
 NaN 
 1.49368 
 0.670023 
 0 
 1 
 1 
 2 
 5 
 
 
 codigo_ciiu 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 387.611 
 1634.03 
 0 
 10 
 10 
 10 
 9900 
 
 
 ind_mora_vigente 
 9527193 
 1 
 True 
 9527193 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 cartera_castigada 
 9527193 
 1 
 True 
 9527193 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 ciudad_residencia 
 9526350 
 1711 
 BOGOTA D.C. 
 2634338 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 mora_max 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 3.6386 
 19.8764 
 0 
 0 
 0 
 0 
 3367 
 
 
 cant_moras_30_ult_12_meses 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 0.0505194 
 0.472796 
 0 
 0 
 0 
 0 
 12 
 
 
 cant_moras_60_ult_12_meses 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 0.0255511 
 0.356678 
 0 
 0 
 0 
 0 
 12 
 
 
 cant_moras_90_ult_12_meses 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 0.0167688 
 0.292358 
 0 
 0 
 0 
 0 
 12 
 
 
 cupo_total_tc 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 6.28941e+06 
 1.31279e+07 
 0 
 0 
 0 
 7.7e+06 
 9.662e+08 
 
 
 tenencia_tc 
 9527193 
 2 
 False 
 4910367 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 cuota_tc_bancolombia 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 268202 
 699790 
 0 
 0 
 0 
 296000 
 1.18706e+08 
 
 
 tiene_consumo 
 9527193 
 2 
 False 
 7767426 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 tiene_crediagil 
 9527193 
 2 
 False 
 7609822 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 nro_tot_cuentas 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 1.10458 
 0.459495 
 0 
 1 
 1 
 1 
 36 
 
 
 ctas_activas 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 1.03458 
 0.409644 
 0 
 1 
 1 
 1 
 36 
 
 
 tiene_ctas_activas 
 9527193 
 2 
 True 
 8973732 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 ctas_embargadas 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 0.00305337 
 0.057891 
 0 
 0 
 0 
 0 
 4 
 
 
 tiene_ctas_embargadas 
 9527193 
 2 
 False 
 9203902 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 pension_fopep 
 9527193 
 2 
 False 
 8963825 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 tiene_cred_hipo_1 
 9527193 
 2 
 False 
 9228426 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 tiene_cred_hipo_2 
 9527193 
 2 
 False 
 9228426 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 mediana_nom3 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 1.43265e+06 
 2.92597e+06 
 0 
 0 
 0 
 2.1248e+06 
 5.8263e+08 
 
 
 mediana_pen3 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 217806 
 1.09923e+06 
 0 
 0 
 0 
 0 
 8.25295e+08 
 
 
 ingreso_nompen 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 1.65045e+06 
 3.04974e+06 
 0 
 0 
 0 
 2.44629e+06 
 8.25295e+08 
 
 
 ingreso_final 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 4.79009e+06 
 7.57905e+06 
 0 
 1.902e+06 
 3.1162e+06 
 5.3e+06 
 6.67855e+09 
 
 
 cant_mora_30_tdc_ult_3m_sf 
 9.52719e+06 
 NaN 
 NaN 
 NaN 
 0.0214512 
 0.187086 

In [71]:
inputs.dtypes

id_registro                       object
periodo                            int64
id_cli                             int64
fecha_nacimiento                 float64
edad                             float64
genero                            object
estado_civil                      object
nivel_academico                   object
profesion                         object
ocupacion                         object
ult_actual                       float64
categoria                        float64
codigo_ciiu                      float64
ind_mora_vigente                    bool
cartera_castigada                   bool
ciudad_residencia                 object
mora_max                         float64
cant_moras_30_ult_12_meses       float64
cant_moras_60_ult_12_meses       float64
cant_moras_90_ult_12_meses       float64
cupo_total_tc                    float64
tenencia_tc                         bool
cuota_tc_bancolombia             float64
tiene_consumo                       bool
tiene_crediagil 

In [72]:
inputs.info()

<class 'modin.pandas.dataframe.DataFrame'>
Int64Index: 9527193 entries, 0 to 9527192
Data columns (total 56 columns):
 #   Column                         Non-Null Count    Dtype  
---  -----------------------------  ----------------  -----  
 0   id_registro                    9527193 non-null  object
 1   periodo                        9527193 non-null  int64
 2   id_cli                         9527193 non-null  int64
 3   fecha_nacimiento               9527193 non-null  float64
 4   edad                           9527193 non-null  float64
 5   genero                         9527193 non-null  object
 6   estado_civil                   9526675 non-null  object
 7   nivel_academico                9527193 non-null  object
 8   profesion                      9477607 non-null  object
 9   ocupacion                      9527177 non-null  object
 10  ult_actual                     9527193 non-null  float64
 11  categoria                      9523869 non-null  float64
 12  codigo_ciiu        

In [73]:
inputs.to_csv('/mnt/workstation/data/Alomarrano/test_inputs3.csv')